### PR TITLE
Fixed depedencies in pathio by editing makefile

### PR DESCRIPTION
**Pull request by alsmola**
This change adds dependencies to the `Godep.json` and `/vendor` directory that are introduced by running `godep save ./...`. 

I'm not sure why this somehow got out of sync - it looks like `kingpin` is required by `cmd/p3.go`, but I can't see where `sts` is required. It's possible my `godep` configuration or command is wrong. I'd appreciate if someone could run locally and see if they get the same results.

I will rebase https://github.com/Clever/pathio/pull/8 off of this once it's merged, which should help reduce the size of that pull request.

### CODE REVIEW

**Comment by natebrennand** [comment]
@alsmola: We're still figuring out as a company how we want to do vendoring.
Generally our current move is to add a Makefile target to pull in the necessary dependencies:

```make
PKG = github.com/Clever/pathio
PKGS := $(PKG) github.com/Clever/pathio/cmd

GODEP=$(GOPATH)/bin/godep

$(GODEP):
	@go get -u github.com/tools/godep

vendor: $(GODEP)
	$(GODEP) save $(PKGS)
	find vendor/ -path '*/vendor' -type d | xargs -IX rm -r X` # remove any nested vendor directories
```

---

When you call `godep save ./...` it will bring in dependencies that often are not necessary. This happens when a nested directory of a dependency has other imports. We have this issue with our thrift services often because the generated code includes an executable that pulls in more libraries.

----

As for the `kingpin` dependency, we're actually already tracking and importing it with the `gopkg.in/alecthomas/kingpin.v2`import path. I think your recursive save call found a path somewhere in the library that was not properly rewritten to use the `gopkg.in` path.

----

Can you try editing the Makefile as suggested and see if it changes the godep behavior?

**Comment by rgarcia** [comment]
sorry for chiming in late, but IMO we should not vendor in libraries, only in binaries. `pathio` is a library

**Comment by natebrennand** [comment]
@alsmola: I think that is now standard behavior with `godep`, I'm not sure if it changed at any point.

@rgarcia: I agree, but how do you feel about maintaining a `Godeps/Godeps.json` without the actual vendored files? I think it might be useful to at least have a reference to what versions of the library work as expected.

**Comment by rgarcia** [comment]
@natebrennand has needing this reference ever been useful? If I'm understanding correctly, this would help us in the case of a library malfunctioning when included in a binary. With the `Godeps.json` file in the library, you could then attempt to change the binary to use the last-known-correct dependencies of the library. I can't remember a time when we've needed this.

I'd also argue that if the above happens, it's code debt in the library that will compound with every binary that includes the library. I'd much rather put the effort into fixing the library vs. finagling the import versions of the binary.

**Comment by alsmola** [comment]
@rgarcia can you point me to a library repo that handles dependencies correctly? I can try to mirror that approach.

**Comment by natebrennand** [comment]
@rgarcia: I've never encountered an issue from this personally.
Mostly echoing concerns @cgclever had in the past about aws-sdk-go's lack of stability.

----

@alsmola: the approach suggested is that you call `go get .` from drone prior to running `go test`. Kayvee-go is an example repo: https://github.com/Clever/kayvee-go/blob/master/Makefile#L19.

**Comment by alsmola** [comment]
@natebrennand waiting for a review on whether the latest commit is the right approach here.

**Comment by natebrennand** [comment]
:+1: lgtm

**Pull request merged**
